In [8]:
import numpy as np # Imports the NumPy library

a = np.zeros(3) # Makes a row vector 'a' of zeros
print(a) # Displays vector 'a'


[0. 0. 0.]


In [21]:
a = np.linspace(1,4,4) # 1 to 4, 4 elements

print(a)
print(a[1]) # Select element within 'a'

z = int(a[1]) # Change element 1 from 'a' to an integer
print(z)

[1. 2. 3. 4.]
2.0
2


In [23]:
type(a) # Check type
type(z)

int

In [24]:
z == a # Check where z = a

array([False,  True, False, False])

In [38]:
pi = np.pi # Pi
print(pi)

e = np.e # Eulers number
print(e)
a = np.sin(1/2) # Sine
print(a)

b = np.arcsin(pi/4) # Arcsine
print(b)

c = np.tan(1/2) # Tangent
print(c)

0.479425538604203
0.9033391107665127
0.5463024898437905
